### PR TITLE
Make exit code useful

### PR DESCRIPTION
**Pull request by twaugh**
Signed-off-by: Tim Waugh <twaugh@redhat.com>

### CODE REVIEW

**Review by vkrizan — APPROVED** [review]
LGTM.

Have you considered skipping exit code `2`, which is standardized for shell utility missuse?

**Comment by twaugh** [comment]
Oh good point.

**Comment by RalphCorderoy** [comment]
Hi @vkrizan, I'm aware exit(1p) reserves the meaning of [126, 255). What standard are you referring to? I see bash(1) says _All builtins return an exit status of 2 to indicate incorrect usage_; is that it? Only zsh doesn't do that, for example, its `syswrite` returns 2 for a write error, and its `zsystem flock` uses 2 for a timeout, as two examples.

**Comment by vkrizan** [comment]
Hi @RalphCorderoy, I've found it in https://www.tldp.org/LDP/abs/html/exitcodes.html I am not sure how actual the document is. Anyway using the `exit(2)` is fine by me.

**Pull request merged**
